dev:
  opAsseticPlugin:
    enable_css: false
    enable_js: false

all:
  opAsseticPlugin:
    enable_css: true
    enable_js: true
    minify_css: true
    minify_js: true
    use_minify_cache_css: true
    use_minify_cache_js: true
